version: '3.9'

networks:
  cassandra:
services:
  cassandra:
    image: cassandra:latest
    networks:
      - cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./data/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra
      - CASSANDRA_LISTEN_ADDRESS=localhost
  postgresql:
    image: postgres:latest
    networks:
      - cassandra
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=demo_password
      - PGDATA=/var/lib/postgresql/data/pgdata