[project]
name = "demo"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
license = {text = "Proprietary"}

dependencies = [
    "pyspark==3.5.0",
]

[tool.setuptools.packages.find]
include = ["demo"]
